compiler/CMakeLists.txt
Also it seems that the Xcode ctags does not handle "-R" so I put it behind a check.
=> OS X CMake fixes

libraries/filters.lib
Correct description of mth_octave_filterbank_default
=> Fix documentation in filters.lib

architecture/owl.cpp, tools/faust2appls/faust2owl
Added support for buttons in architecture file.
Fixed issue with `faust2owl` script.
Added custom memory management for OWL architecture.
Added -mem flag to OWL script.
=> bringing code up to date with OWL architecture and script changes

architecture/owl.cpp
=> updated to latest version, and no longer using placement new

libraries/physmodels.lib
from #66 . Changed branch to master-dev.
=> Changed the coefficient of lip filter according to original STK's way.

tools/faust2appls/faust2supercollider
I have modified the faust2supercollider script to additionally build the supernova version on linux.
=> also build supernova lib with faust2supercollider

compiler/Makefile.unix, compiler/generator/llvm/llvm_code_container.cpp, compiler/generator/llvm/llvm_code_container.hh, compiler/generator/llvm/llvm_dsp_aux.cpp, compiler/generator/llvm/llvm_dsp_aux.hh, compiler/generator/llvm/llvm_instructions.hh, compiler/signals/binop.cpp
Required a few changes, mainly just adding the LLVM_60 macro.
I understand if you'd rather keep this out until clang 6 is released,
but its very helpful to me, and i thought i'd share it!
Keep up the good work, we're using faust heavilly over on the
[OTTO](https://github.com/topisani/OTTO), and very happy with it!
=> Build on clang 6.0.0 svn

architecture/httpdlib/src/Makefile, architecture/osclib/Makefile, architecture/osclib/faust/Makefile, compiler/Makefile.unix, compiler/errors/exception.hh
Make the sources compile on Windows with mingw32+64 in the msys2 environment.
=> mingw fixes

Makefile, build/CMakeLists.txt, build/Makefile, build/README.md, build/http/CMakeLists.txt, build/osc/CMakeLists.txt
+ makefile: targets adjustments (compiler, osc and http are now compiled by default)
=> documentation

architecture/faust/dsp/llvm-c-dsp.h
The commit fixes this [issue](https://github.com/grame-cncm/faust/issues/176)
=> Fixed error C2016 with MSVC - C API

compiler/Makefile.unix
Add LLVM version 6.0.1 to Makefile.unix
=> Add LLVM version 6.0.1 to Makefile.unix

tools/faust2appls/faust2bela
=> Small bela fix

architecture/webaudio/webaudio-wasm-wrapper.js
I'm getting error while using JSON.parse on it.
=> Illegal comma after last value in JSON object

architecture/unity/FaustPolyUtilities_template.cs, architecture/unity/FaustUtilities_template.cs
Tested and works fine for both editor and standalone. Fix #240
=> Unity utilities script import dll correctly on linux

architecture/webaudio/webaudio-wasm-wrapper.js
channel is not defined here, changed to channel 0.
=> fix error on calling allNotesOff of WorkletNode

architecture/bela.cpp, tools/faust2appls/faust2bela
`faust2bela` and `architecture/bela.cpp`.
Closes grame-cncm/faust#256
=> Bela fixes

architecture/webaudio/npm/package.json, architecture/webaudio/webaudio-workletnode-poly-standalone-wrapper.js, architecture/webaudio/webaudio-workletnode-standalone-wrapper.js
=> npm module support for webaudio standalone wrapper

compiler/generator/llvm/llvm_dsp_aux.cpp
Fix for https://github.com/grame-cncm/faust/issues/306
=> llvm: Fix lock position in ~llvm_dsp

compiler/global.cpp, tests/llvm-tests/llvm-test.cpp
Make llvm-test temp directory configurable
=> Double the Machine Pointer Size when under 32bit Android

tools/faust2appls/faust2puredata, tools/faust2appls/faustpath
including guessing Pd path on Linux, and generating only the source code for Pd with `-tosource`
=> more fixes on faust2puredata

architecture/httpdlib/html/faust.html, architecture/httpdlib/html/js/faust_webaudio_tools.js
- `XMLHttpRequest`
- `fetch`
- `AudioBufferSourceNode#noteOn`
- `AudioBufferSourceNode#start`
- `AudioBufferSourceNode#noteOff`
- `AudioBufferSourceNode#stop`
- ES5 syntax
- ES2015 ~ syntax
=> Use the latest APIs instead of legacy APIs

architecture/lv2.cpp, architecture/lv2ui.cpp, tools/faust2appls/faust2lv2
Correct some problems with Faust's current LV2 generator.
edit: finished, good for review
=> Fixes to LV2

README.md
closes #457
The issue seems to be somehow related to this: https://stackoverflow.com/questions/21337276/ios-app-asks-for-microphone-access-even-for-kaudiosessioncategory-mediaplayback
and this: alexbw/novocaine#76
=> Enable AudioUnit's input only when fDevNumInChans > 0

tests/compile-time-tests/bug127.dsp
As discussed in #127. Anyone who's running the regression tests at Grame please review and merge, thanks.
=> Add regression test for #127.

benchmark/alsa-gtk-bench.cpp, benchmark/mixer.dsp
Came across some errors while trying to run the benchmarks. I was able to work around it by updating some of the include and class declarations.
=> Update libraries and class definition conflict

architecture/esp32/esp32.cpp, architecture/faust/gui/Esp32Reader.h
Make the generated code compilable
=> esp32: fix soundfile support

syntax-highlighting/faust-mode.el
fixes https://github.com/rukano/emacs-faust-mode/issues/15
=> update emacs-faust-mode for use with emacs 27

tools/physicalModeling/ir2dsp/ir2dspoly.py
fixed the ir2dsp python script so that it scales the values correctly and creates a correct sound upon testing / comparison with audio file.  Created the initial version of a poly ir2dsp script that scales all the frequency values to ratios and allows playing everything with midi.
=> fix ir2dsp and add poly ir2dsp

architecture/minimal-jack.rs, architecture/minimal-portaudio.rs, architecture/minimal.rs
Bring minimal.rs up-to-date, and improve ergonomics when communicating ParamIndex from external call-site
=> Fix Rust architecture files

compiler/generator/dlang/dlang_code_container.cpp, compiler/generator/dlang/dlang_code_container.hh, compiler/libcode.cpp
Implements the 1-sample generator for D.
A simplistic and incomplete architecture file for testing it.
```
struct Meta {
@nogc:
void declare(string, string) nothrow {}
}
struct UI {
@nogc:
void declare(float*, string, string) nothrow {}
void openVerticalBox(string) nothrow {}
void closeBox() nothrow {}
void addCheckButton(string, float*) nothrow {}
void addHorizontalSlider(string, float*, float, float, float, float) nothrow {}
void addHorizontalBargraph(string, float*, float, float) nothrow {}
}
class one_sample_dsp {
@nogc:
}
alias FAUSTFLOAT = float;
<<includeIntrinsic>>
<<includeclass>>
```
=> One sample generator for dlang

architecture/bench.d
It's a port of the architecture `bench.cpp` from C++ to D.
It's written in `@nogc` and `@trusted` constraints, which means no intervention of GC, and no bounds check.
=> Add a benchmarking architecture for dlang

tools/faust2appls/faust2esp32
change -es8338 flag to -es8388
=> fix typo in help

examples/quantizing/quantizedChords.dsp
I added an example on how to use the quantizers library.
@rmichon
=> quantizers example

examples/quantizing/quantizedChords.dsp
Changed the example in hope it would be easier to understand.
=> Improved readability

architecture/audiokit/FaustDSP.mm, architecture/audiokit/SwiftGenerator.cpp
generates a working AKv5 Node that can be dropped into a project and used like other AK Nodes
github.com:misterinterrupt/Faust2AudioKitExample.git uses generated code from this commit dragged into a small app
=> adjustments to generated output

architecture/juce/plugin/plugin.jucer, tools/faust2appls/faust2juce
See: https://github.com/grame-cncm/faust/issues/585
=> Fix for issue #585, creating VST3 via JUCE

tools/faust2appls/faust2juce
=> Issue 589 IS_SYNTH faust2juce

compiler/libcode.cpp
Noticed while checking how all of this works ;p
=> Fix a small typo in an error message

tools/faust2appls/faust2sc.py
Fixes https://github.com/grame-cncm/faust/issues/702
=> Faust2scpy replace whitespace with underscores in arguments

tools/faust2appls/faust2sc.py
feat: Add --faustflags option to faust2sc.py
=> feat: Interpret additional flags of faust2sc.py as other tools do

tools/faust2appls/faust2vst
replace with arm64 for universal build
=> Remove i386 architecture from faust2vst/Darwin

compiler/transform/signal2vhdlVisitor.cpp, compiler/transform/signal2vhdlVisitor.hh
hi Stephane, I hope I didn't overwrite some of the cleanup you already did this morning...
=> [faust2vhdl] use tree serial instead of pointer addr for uid + fix float coding issue + some cleanup

compiler/transform/signal2vhdlVisitor.cpp, compiler/transform/signal2vhdlVisitor.hh
this should be clean (hopefully...)
=> [faust2vhdl] fixes suffix/signal type conflicts

architecture/faust/dsp/libfaust-signal.h, compiler/garbageable.hh, compiler/signals/signals.cpp, compiler/signals/signals.hh, compiler/tlib/list.cpp, compiler/tlib/list.hh, compiler/tlib/recursive-tree.cpp, compiler/tlib/tree.cpp, compiler/tlib/tree.hh
These changes have been useful for my Python signal API experiment.
* add isSig* functions to signal API.
* Make CTree and Garbageable exported with LIBFAUST_API
=> signal api changes

examples/gameaudio/fire.dsp
Just a small example. Result of two evenings of experimentation. I think the result is pretty good taking into account the size and complexity of the file.
=> New example - gameaudio/fire

examples/gameaudio/cricket.dsp
The sound is based on an example from the book "Designing Sound" by Andy Farnell. Better triggering system is added.
=> New example - gameaudio/cricket

architecture/faust/dsp/libfaust-signal-c.h, architecture/faust/dsp/libfaust-signal.h, compiler/libcode.cpp, compiler/tlib/tree.cpp, compiler/tlib/tree.hh
This change is helping with the Python API.
=> export getUserData with LIBFAUST_API

architecture/teensy/teensy.h
=> For Teensy, replace fprintf with Serial.printf

tools/faust2appls/faust2tidalcycles
added -noprefix to faust2supercollider
=> fixed -noprefix in faust2tidalcycles 

.github/workflows/libfaust.yml
I can run the libfaust action with the checkbox for making a draft release and it resulted in a draft release with all of the artifacts.
=> Draft release action

.github/workflows/libfaust.yml
This fixes the libfaust Ubuntu zip and faustgen windows zip.
=> Fix GitHub Action for drafting a release

tools/faust2appls/faust2cagtk, tools/faust2appls/faust2caqt, tools/faust2appls/faust2jack, tools/faust2appls/faust2jaqt
Fixes https://github.com/grame-cncm/faust/issues/899
=> make preset management thread safe

compiler/global.cpp
Follow up to https://github.com/grame-cncm/faust/issues/875#issuecomment-1640221245
=> Use repr(C) by default

compiler/generator/jsfx/README.md, compiler/generator/jsfx/jsfx_instructions.hh
Improved code, added comments and README.
=> Jsfx improvements

compiler/extended/exp10prim.hh, compiler/extended/log10prim.hh, compiler/extended/logprim.hh, compiler/extended/sqrtprim.hh, compiler/generator/type_manager.hh, compiler/interval/check.cpp, compiler/interval/check.hh, compiler/interval/intervalAcos.cpp, compiler/interval/intervalAcosh.cpp, compiler/interval/intervalAsin.cpp, compiler/interval/intervalAsinh.cpp, compiler/interval/intervalAtan.cpp, compiler/interval/intervalAtanh.cpp, compiler/interval/intervalCos.cpp, compiler/interval/intervalCosh.cpp, compiler/interval/intervalInv.cpp, compiler/interval/intervalLog.cpp, compiler/interval/intervalLog10.cpp, compiler/interval/intervalMissing.cpp, compiler/interval/intervalMod.cpp, compiler/interval/intervalPow.cpp, compiler/interval/intervalSin.cpp, compiler/interval/intervalSinh.cpp, compiler/interval/intervalSqrt.cpp, compiler/interval/intervalTan.cpp, compiler/interval/intervalTanh.cpp, compiler/interval/interval_def.hh, compiler/interval/precision_utils.hh
In particular when the interval computation detects some domain violation.
=> Corrects the computation of MSB and intervals

architecture/daisy/ex_faust.cpp, architecture/faust/gui/DaisyPatchInitControlUI.h, tools/faust2appls/faust2daisy
This adds a GUI class for the Daisy Patch.Init Eurorack module, based on the existing DaisyControlUI class.
The ifdefs are possibly looking a bit unwieldy, I'm down to help think through this more broadly.
The `KnobContext` et. al should be shared with DaisyControlUI.
Discussion welcome!
=> Preliminary support for the Daisy "Patch.Init" Eurorack module device

.github/workflows/macos.yml, .github/workflows/ubuntu.yml, .github/workflows/windows.yml
This shoudl fix a bad if condition from https://github.com/grame-cncm/faust/commit/2dfa3a2ef7b865f44fa805659c21f82b879c576b
=> fix if condition in github actions

architecture/stratus.cpp, tools/faust2appls/faust2stratus
Tighter C++ code in the architecture file
Fixed output handling and better help doc in the generator script
=> Cleanups, tweaks, and fixes for the Chaos Audio Stratus pedal

architecture/chaos-stratus/README.txt, architecture/chaos-stratus/_pedal-tools.sh, architecture/chaos-stratus/build-effect.sh, architecture/chaos-stratus/build-install-effect.sh, tools/faust2appls/faust2stratus
* Replacing realpath with a dodgy but working native BASH expression
* Enabling docker-based builds for local invocations of faust2stratus
* Enabling docker-based builds when running the faustservice-generated installer
* A readme for the install process
=> Final (hahaha) tweaks

architecture/faust/gui/DecoratorUI.h, tools/faust2appls/faust2daisy
adressing #1090
missing } in DecoratorUI.h
Missing DAISY flag. Added preprocessor flag to faust2daisy tool.
=> Minor fixes to daisy polyphony

compiler/draw/sigToGraph.cpp
fixes faust2sig / dot file generation
=> Fix for the issue #549

architecture/daisy/README.md, tools/faust2appls/faust2daisy
As discussed on Discord.
These bits are incorrect (there might be more, but these are the ones I could find easily).
=> update documentation and help
