grame-cncm/faust

compiler/Makefile.unix
Hi Stéphane, can you please review this and merge? I need this to build faust2 against LLVM 3.4 for MacPorts. Compilation is currently broken for LLVM < 3.5 because these don't have the `llvm-config --system-libs` option yet.
This shouldn't cause any changes with any of the newer versions (3.5+). I tested with LLVM 3.4.2, 3.5.2 and 3.9.1 from MacPorts and it works fine with each of these.
=> Fixes for LLVM 3.4 compatibility.

tools/faust2appls/faust2juce
"faust2juce" breaks when run on source files that are located in a subdirectory. This patch fixes that bug.
=> fix "faust2juce" for source files in a subdirectory

architecture/supercollider.cpp
It seems like some options that were required for SuperCollider, and that were reported had not been properly added. This PR should fix this.
Applied PR to master-dev branch as requested by @sletz.
=> Add appropriate options to the SC generator

compiler/generator/llvm/llvm_dsp_aux.cpp
See https://github.com/grame-cncm/faust/issues/38
=> static_cast to prevent gcc compilation error, fixes #38

architecture/supercollider.cpp
These definitions are required to support supernova, the  multiprocessor SuperCollider server. They have no effect outside of Supercollider build scripts with Supernova enabled.
@LFSaw asked me to take my supernova enabler for his JPverb upstream to you.
https://github.com/supercollider/sc3-plugins/pull/149
=> support supernova

architecture/unity/FaustUtilities_template.cs
This is required for deploying to Unity WSA apps, e.g. for HoloLens and mixed reality
=> Unity: add support for Windows Store Apps

tools/faust2appls/faust2linuxunity, tools/faust2appls/faust2w32unity, tools/faust2appls/faust2w64unity
This fixes a problem with generated dlls not being found in Unity.
The compiled dlls should have the `lib` prefix, as replaced by sed in
`faust2unity`
`sed -e "s/MODEL/$NAME/g;s/PLUGNAME/lib$FNAME/`
Currently they just use $FNAME, this adds the `lib` prefix
=> Unity: fix lib prefix for binaries

architecture/csound.cpp
The Microsoft compiler does not permit the declaration of zero size arrays. This commit makes each array in the dataspace struct for the Csound template have a minimum size of 1.
=> Minimum dataspace array sizes of 1 for Microsoft C++ compiler.

architecture/pure.c
this change required in order to successfully run "make bitcode" for pure-lang's pd-faust framework
(@agraef - still haven't managed to get pd-faust compiling/working correctly against recent faust, pd & pure-lang repositories but this is surely a step in the right direction)
=> fix bitcode compile for pure-lang/pd-faust

architecture/supercollider.cpp, tools/faust2appls/faust2supercollider, tools/faust2sc-1.0.0/faust2sc
We added the option -noprefix to the faust2supercollider script. Default behavior remains the same as previous: "Faust" is used as prefix. 
With the -noprefix option, the resulting UGen class name comply with supercollider3 naming conventions. 
This follows the discussion #131
=> adding the -noprefix option to faust2supercollider script

Makefile, build/backends/world.cmake
This makes `make world` do what it's supposed to do again.
@dfober, this does what I need now, thanks for the many explanations in pm. I'll merge this right away (as soon as CI finishes)  so that I can go on with my package builds. I think that I didn't accidentally break any of the other targets, but if you notice anything dubious in my changes, please let me know, so that I can fix any remaining issues.
=> World target fixes

compiler/global.hh
Fixed a type declaration warning: the variable `DeclareStructTypeInst` is a **struct** - [l. 1321 of instruction.hh](https://github.com/grame-cncm/faust/blob/00a03871a26d0371f1dd33a0791e6ab3070e3e3a/compiler/generator/instructions.hh#L1321) - but is re-declared as a **class**  - [l. 61 of compiler/global.hh](https://github.com/grame-cncm/faust/blob/master-dev/compiler/global.hh#L61).
=> Fixed struct type declaration

build/CMakeLists.txt
The **faust** runtime executable is not always necessary and can be a bit annoying when using FAUST as a subdirectory in another CMake project (using `add_subdirectory()`). This option allows to remove the target **faust** (runtime executable  target) if needed - if a project only requires the static and/or the dynamic libraries for example. The target **faust** is always enable by default.
=> Add a CMake option for the runtime executable target

architecture/faust/gui/CInterface.h
Fix the use of the Soundfile struct for the C API
=> fixed struct declaration for Soundfile

architecture/faust/gui/GUI.h, architecture/jack-gtk.cpp
This PR adds the `GUI::runAllGuis()` function, and refactors the `jack-gtk.cpp` architecture to use it.
=> Refactor gui run

architecture/minimal-portaudio.rs, tools/faust2appls/faust2portaudiorust
The rust backend could use jack as architecture.
I have added support to portaudio, through rust-portaudio.
I have put a faust2rportaudiorust in the tools directory.
rust-portaudio does not support non-interleaved streams so I had to use some unsafe functions to transform a pseudo interleaved stream into non interleaved streams, without copying...
=> Rust portaudio backend

compiler/generator/llvm/llvm_dsp_aux.cpp, compiler/parser/sourcefetcher.cpp
I had to perform these changes to build the latest commit - the first (order of extern "C" and export) should not break anything - and I guess the second one neither since <errno.h> is included, thus making that errno declaration redundant.
=> build fixes on archlinux

tools/physicalModeling/ir2dsp/ir2dsp.py
The generated output of `ir2dsp.py` did not compile with faust due to missing environment prefixes. Also the argument order of `pm.modalModel(...)` was in wrong order.
Please note that in https://github.com/grame-cncm/faustlibraries/blob/master/physmodels.lib the environment prefix to `take` is still missing and the use of `modalFilter` is wrong. `gain(i)*modeFilter(freqs(i),res(i))` should be changed to `modeFilter(freqs(i),res(i),gain(i))`.
=> Fix ir2dsp

architecture/bela.cpp, architecture/faust/gui/BelaOSCUI.h, tools/faust2appls/faust2bela
The polarity of digital inputs was wrong: a `0` meant `fMin + range`, a `1` meant `fMin`. Fixed.
The `BelaOSCUI` was not compiling. Fixed.
Added support for an `httpdUI`-based GUI to the architecture file and `faust2bela`.
=> A number of Bela fixes

compiler/tlib/compatibility.hh
clang masquerades itself as a GCC 4.2.1 (https://lists.llvm.org/pipermail/llvm-dev/2011-February/038151.html) even though it is able of much more (in my case it's clang-8) ; this fixes a redefinition of struct timezone in that case.
=> Fix compatibility.hh on MinGW with clang

compiler/generator/llvm/llvm_code_container.cpp, compiler/generator/llvm/llvm_dsp_aux.cpp, compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp, compiler/generator/llvm/llvm_instructions.hh
This patch adds support for building with LLVM 8 - there weren't any apparent breaking API changes thankfully so I just did follow the same pattern than for LLVM 7. 
Some can still happen but as far as I know the LLVM8 feature freeze should be sometimes in january so hopefully nothing more will break until then :-)
=> Add support for LLVM 8

Makefile
there was a missing `"` which caused 
```
/bin/sh: -c: line 0: unexpected EOF while looking for matching `"'
/bin/sh: -c: line 1: syntax error: unexpected end of file
make: *** [help] Error 2
```
when running `make help`
=> fix make help

architecture/unity/FaustPolyUtilities_template.cs
Hi, thanks for the great repository.
I tried `faust2unity` converter and it throws DllNotFound error on iOS. the DLL name should be `__Intanal` on iOS-unity platform. 
Tested on 
- Unity Version: 2018.3.4f1
- Xcode: 10.1
=> Fix DLL name on iOS in the unity template

compiler/generator/description.cpp, compiler/generator/description.hh, compiler/libcode.cpp
This is a lack of the XML report in comparison to the JSON one.
I add the metadata from the global set, actives and passives.
It's in the form `<meta key="foo">bar</meta>`.
Remark: I have also noted that JSON lacks some information that XML has: `varname`
=> Report the metadata in XML output

architecture/alsa-console.cpp
alsa-console.cpp refers to JSONUI (see e.g. https://github.com/grame-cncm/faust/blob/f1985b49b74ec520a076e9d7f76793a5e3bea72f/architecture/alsa-console.cpp#L106) but JSONUI.h is not included at the top of the file. This PR adds it.
=> Fix architecture file for faust2alsaconsole

embedded/faust4processing/src/faust-libraries/filter.lib, tests/impulse-tests/dsp/filter.lib
I saw the typo in https://faust.grame.fr/doc/libraries/index.html#arbritary-crossover-filter-banks-and-spectrum-analyzers and tried to fix it. Not sure if it's generated from these files
=> Fix some typos

tools/sound2faust/Makefile
As discussed in #302, sound2{faust,file} lack [full RELRO](https://mudongliang.github.io/2016/07/11/relro-a-not-so-well-known-memory-corruption-mitigation-technique.html), which is caused by `tools/sound2faust/Makefile` being unaware of `LDFLAGS`.
This pull request adds `LDFLAGS` to the `CXX` call and additionally calls pkg-config more cleanly in a shell environment.
=> tools/sound2faust/Makefile: Adding LDFLAGS

tools/faust2appls/faust2atomsnippets, tools/faust2appls/faust2md
As discussed in #301, this drops support for soon EOL Python2 functionality in faust2{md,atomsnippets} and renders these scripts fully compatible with python3.
Additionally, these scripts are now PEP8 conform, which will make further development more easy.
Both scripts share a lot of functionality, which introduces a lot of boilerplate code. This suggests the creation of a unified python library, for which these scripts will only be [entry_points](https://setuptools.readthedocs.io/en/latest/setuptools.html#new-and-changed-setup-keywords).
That's not in the scope of this pull request though!
=> Switch to python3 for faust2{md,atomsnippets}

tools/faust2appls/faustpath
This makes `faust2puredata` usable again
=> Better guess at Pd's include path on macos, and allow override with env variable

compiler/utils/exepath.cpp
Since CMAKE by default ignores your default c/c++ compiler and uses something inside /usr/bin instead, it often happens that faust is compiled with an older version of gcc.
P.S. Maybe add something like this to the makefile?
```
-DCMAKE_CXX_COMPILER=`which g++` -DCMAKE_C_COMPILER=`which gcc"
```
=> Small fix for gcc 4.8.*

Dockerfile
Probably since the latest Debian stable `pkg-config` was not installed as a dependency, but the CMake script relies on it.
Tested on:
- Ubuntu 19.10 with Linux 5.3.0-29-generic
- Docker version 19.03.2, build 6a30dfca03
=> The Docker image needs pkg-config

architecture/webaudio/component-creator.html, architecture/webaudio/faustlive-wasm.html, architecture/webaudio/webComponent/template/faustTemplate.html, architecture/webaudio/webaudio-wasm-emcc-footer.html, architecture/webaudio/webaudio-wasm-emcc-poly-footer.html, architecture/webaudio/webaudio-wasm-emcc-poly-worklet-footer.html, architecture/webaudio/webaudio-wasm-emcc-worklet-footer.html, architecture/webaudio/webaudio-wasm-footer.html, architecture/webaudio/webaudio-wasm-poly-footer.html, architecture/webaudio/webaudio-wasm-poly-worklet-footer.html, architecture/webaudio/webaudio-wasm-worklet-footer.html
Use `MediaDevices` because of `navigator.getUserMedia` is deprecated API ([NOTE](https://www.w3.org/TR/mediacapture-streams/#legacy-interface-extensions)).
=> Use `MediaDevices` instead of deprecated API for `getUserMedia`

tools/faust2appls/faust2jackrust, tools/faust2appls/faust2portaudiorust
A tiny bugfix for the `faust2*rust` scripts:
Currently the `cargo new` happens in the working directoryi, i.e., if the working directory is different from `$SRCDIR` the project is directed in the wrong place. The script will basically fail in
```
faust -a $ARCHFILE -lang rust "$SRCDIR/$f" -o "$SRCDIR/$dspName/src/main.rs"
```
with
```
ERROR : file '<ACTUAL-PROJECT-PATH>/src/main.rs' cannot be opened
```
because the parent directories don't exist.
=> Fixed path handling in faust2*rust scripts

.dockerignore
It turned out that the problem I observed in #430 was because I had local build artifacts that got copied into the docker image and then messed up the cmake run.
There is a simple solution: Exclude `build/faustdir` from getting copied into the docker image via a `.dockerignore`.
CC @gierschv
=> added .dockerignore to avoid copying host build artifacts into docker

tools/faust2appls/faust2api
```
$faust2api -ios -target folder -nozip test.dsp
Your folder.zip API package for iOS is being created
$ls
DspFaust.cpp	DspFaust.h	README.md	test.dsp
```
`-target` option is being ignored when `-nozip` parameter is specified. API files are moved into `.`.
Without `-target` option it behaves exactly the same:
```
$faust2api -ios -nozip test.dsp
Your dsp-faust.zip API package for iOS is being created
$ls
DspFaust.cpp	DspFaust.h	README.md	test.dsp
``` 
Moreover, the message says
> Your **dsp-faust.zip** API package for iOS is being created
Even though `-nozip` option has been given which might confuse.
1. default: create `dsp-faust.zip` archive
```
$faust2api -ios test.dsp
Your dsp-faust.zip API package for iOS is being created
$ls
dsp-faust.zip	test.dsp
```
2. `-target archivename`: create …
=> Preserve API folder when both -target and -nozip options specified

architecture/minimal-jack.rs, architecture/minimal-portaudio.rs, compiler/generator/rust/rust_code_container.cpp, tests/impulse-tests/archs/rust/architecture.rs
A minor follow-up to #448: As suggested by @bkfox, we can avoid some of the `&mut self` references.
Note: Eventually when `build_user_interface` returns only parameter indices, it can also become immutable. Without touching the interface of the UI functions I had to keep it for now due to the mutable borrows there.
=> [Rust] Removed unnecessary mutable self references

tools/faust2appls/faust2png
remove the extension from the command line argument to match the directory name created by faust2svg
=> extract file name in faust2png

architecture/esp32/drivers/es8388/CMakeLists.txt, architecture/esp32/drivers/es8388/adf_structs.h, architecture/esp32/drivers/es8388/es8388.cpp, architecture/esp32/drivers/es8388/es8388.h, architecture/faust/audio/esp32-dsp.h, tools/faust2appls/faust2esp32
This adds support for the es8388 audio codec, the codec used by the espressif LyraT to faust.
-added three driver files, as well as the relevant makefiles to the faust architecture. They configure the es8388 codec based on input from the user and behave similarly to the wm8978 and ac101 drivers. 
-updated the faust2esp32 to include a -es8388 option, which behaves the same as the options for the other drivers while substituting the relevant es8388 files
-added support for the LyraT to esp32-dsp.h
-fixed a small typo wm8798 -> wm8978 in faust2esp32
the driver files are fully functional but still under development
=> added es8388 driver support

compiler/evaluate/eval.cpp
The bug causes the little state machine in evalLabel (eval.cpp) to "stutter" in some cases (e.g., `%k` becomes `%kk`). Apparently that's because in Release mode the compiler (MSVC from Visual Studio 2019, i.e., the latest one) optimizes the loop so aggressively that it misses out the increment of the `src` pointer when switching to state 2 after the first IdentChar is detected.
We work around this by just dropping the local `char c` variable and using the `src` pointer directly throughout the loop, incrementing it whenever necessary. This solves the issue.
NOTE: This succeeds #485 which was based on another branch. The present PR is ready to be merged into master-dev.
=> Work around a compiler bug in MSVC from Visual Studio 2019 (rebased on master-dev).

compiler/README.md, compiler/generator/dlang/dlang_code_container.cpp, compiler/generator/dlang/dlang_code_container.hh, compiler/libcode.cpp
This implements the flag `-ns` in dlang.
The behavior is that if the option is `-ns foo`, then the module is `foo.mydsp`.
This matches to a file named `foo/mydsp.d` in D's search path for imports; since D's file paths and module naming have to match, having this option is important.
It's slightly different from the bit of implementation present before, which wouldn't introduce the `.` character, but I thought it made more consistency with the cpp one.
Implements also the special case depending whether an architecture file is used or not.
=> Support option -ns with D language

.gitignore, Makefile
Add a convenience for the `make` system, that allows to keep some persistent custom settings in a side file, which is ignored by git versioning.
As an example of `user.mk` file:
`PREFIX = /opt/faust`
=> Convenience for makefile custom settings

architecture/faust/gui/Soundfile.h
To clarify, only the first commit is required to use soundfiles on OWL.
The second one is changed to match documented empty buffer size. It's not required for OWL integration, because I've made a slightly simpler replacement for SoundfileReader class (not using exceptions or stdlib classes). I've also changed that custom class to use empty buffers with 0 samples and it works AFAICT. So we'll probably stick to this behavior unless there would be some known use case where allocating buffers would be required.
=> Soundfile corrections

Makefile, compiler/draw/sigToGraph.cpp, compiler/global.cpp, compiler/global.hh, compiler/signals/interval.hh, compiler/signals/sigtype.cpp, compiler/signals/sigtype.hh, compiler/signals/sigtyperules.cpp
Add annotations for each signal of the signal graph (generated with `-sg`) and a new field the types to handle the fixed-point resolution of the signals.
=> Compute just right, signal graph annotation

compiler/draw/sigToGraph.cpp, compiler/signals/interval.hh
should avoid Return Value Optimization bug with old versions of g++
=> use strings when printing intervals and resolution

build/CMakeLists.txt
Minor CMake improvement so that we don't have to define LLVM_111, LLVM_112  etc...
=> CMake: set minor llvm version to zero in LLVM_xxx macro for recent LLVMs

architecture/faust/gui/JuceGUI.h
Other header files feature guards, so I doubt the omission was voluntary.
=> Add header gards to JuceGUI.h

architecture/juce/README.md, architecture/juce/plugin/plugin-llvm.jucer, architecture/juce/plugin/plugin.jucer, architecture/juce/standalone/standalone-llvm.jucer, architecture/juce/standalone/standalone.jucer, tools/faust2appls/README.md, tools/faust2appls/faust2juce
This PR updates `faust2juce` to Projucer 6.0.8 (build date 22 Mar 2021). As a result, some fields in the Projucer file get renamed, and some get added. Visual Studio 2013 was deprecated and removed. Visual Studio 2019 was added. The `faust2juce` script has a new optional argument `-vst2sdkdir` for a legacy VST 2 SDK folder, which enables the building of dll files as opposed to `.vst3` files. There's a new optional argument `-disable-splash-screen` for disabling JUCE's splash screen. By default, the splash screen is enabled. A bug with `grep "declare nvoices"` was fixed because the metadata might actually be `[nvoices:8]` which wouldn't be found by that grep. I tested on Windows by building a dsp with a process and and effect. The standalone exe, dll, and vst3 all work perfectly. **I have …
=> Faust2juce fixes (mainly for Windows)

architecture/esp32/drivers/wm8978/WM8978.cpp, architecture/esp32/drivers/wm8978/WM8978.h
Additional functions added as per WM8978 datasheet to enable sleep mode for power saving, mono output and speaker boost.
=> Additional functions for WM8978 codec 

architecture/esp32/drivers/wm8978/WM8978.cpp, architecture/esp32/drivers/wm8978/WM8978.h
Additional functions for WM8978 codec; power saving, enable mono output, change sample rate, speaker boost, loopback and automute.
=> Additional functions for WM8978

tools/faust2appls/README.md, tools/faust2appls/faust2feh
Hello
This adds the script `faust2feh` which is basically a small version of `faust2firefox` that uses `feh` (a popular extremely light weight image viewer on linux) as the image viewer.
=> Add faust2feh

.github/workflows/ubuntu.yml, build/http/CMakeLists.txt
libws2_32 was added to target_link_libraries for non-windows platforms
despite being a windows only library. This commit removes it and adds
libmicrohttpd to the ubuntu CI to make sure this target is actually
built.
Originally raised in while testing fix for #649.
=> Fix linux httpd build

syntax-highlighting/README.md, syntax-highlighting/sublime-text/Faust/README.md, syntax-highlighting/sublime-text/Faust/all_lib.sublime-snippet, syntax-highlighting/sublime-text/Faust/button.sublime-snippet, syntax-highlighting/sublime-text/Faust/checkbox.sublime-snippet, syntax-highlighting/sublime-text/Faust/component.sublime-snippet, syntax-highlighting/sublime-text/Faust/def.sublime-snippet, syntax-highlighting/sublime-text/Faust/doc.sublime-snippet, syntax-highlighting/sublime-text/Faust/environment.sublime-snippet, syntax-highlighting/sublime-text/Faust/faust.sublime-completions, syntax-highlighting/sublime-text/Faust/hbargraph.sublime-snippet, syntax-highlighting/sublime-text/Faust/hslider.sublime-snippet, syntax-highlighting/sublime-text/Faust/import.sublime-snippet, syntax-highlighting/sublime-text/Faust/library.sublime-snippet, syntax-highlighting/sublime-text/Faust/process.sublime-snippet, syntax-highlighting/sublime-text/Faust/stdfaust_lib.sublime-snippet, syntax-highlighting/sublime-text/Faust/vbargraph.sublime-snippet, syntax-highlighting/sublime-text/Faust/vslider.sublime-snippet, syntax-highlighting/sublime-text/Faust/with.sublime-snippet, tools/faust2appls/faust2sublimecompletions
This PR proposes to add Sublime Text 4 automatic completions for the standard library and snippets taken from the atom snippets.
I'd like to have that tested a little bit before requesting the merge, this PR can be used for this. Is anyone using Sublime Text 4? @nuchi, maybe?
I wanted to bring as much as possible of the ease of use of faustide to my favorite editor. It resulted in doing more intensive parsing of the `.lib` files in order to extract Usage information, as well as a direct link to the docs:
I don't know about other code editors but Sublime Text is not very generous with the size of the area provided for completion: it has to be a single line and I couldn't figure how to force it to span according to the length of the content.
Some functions from the library have long usage …
=> Sublime Text 4 completions and snippets

syntax-highlighting/sublime-text/Faust/Default.sublime-keymap
Sublime Text default behavior for single quotes is to pair them. This doesn't make sense when editing Faust files, where single quotes refer to delay (or a letrec definition) and not to strings.
This addition overrides the default behavior (for `source.faust` scope).
attn @sletz @Simon-L
=> Override the default keymap for single quote (both insertion and deletion) so that it can be used for delay and letrec definitions

examples/smartKeyboard/elecGuitar.dsp
Previously users were able to select frequencies down to 50 Hz, but all frequencies on the range [50 Hz, 60 Hz] were equivalent to selecting 60 Hz. This commit corrects the minimum frequency value to reflect the frequencies provided to the user through the user interface
Tested in Faust IDE
=> Correct minimum frequency in elecGuitar.dsp

tools/faust2appls/README.md, tools/faust2appls/faust2sc.py
This PR adds a new tool for creating SuperCollider plugins from faust code. It replaces the faust2sc and faust2supercollider tools, fixes most of their problems and has additional features such as the generation of help files, better name resolving, better supercollider header search functionality, target architecture may be set as flag, copy to target folder after compilation and a number of other things -  and last but not least an easier to use command line interface. The script is written in Python 3 to make it easier to maintain in the future as well and has no external dependencies. The script requires Python version 3.8 as a minimum. 
Run `faust2sc.py -h` for more information on usage:
```
usage: faust2sc.py [-h] [-a ARCHITECTURE] [-m MACOSARCH]
[-t TARGETFOLDER] [-n {0,1}] [-s] …
```
=> feat: Add faust2sc.py

architecture/CSharpFaustBase.cs, compiler/generator/csharp/csharp_code_container.cpp, compiler/generator/csharp/csharp_instructions.hh
Added IsInfinity and IsInfinityF to C# base class and removed from codegen. Removed GetInputRate() and GetOutputRate() from IFaustDSP interface.
Fixes issues #686 and #687
=> CSharp fixes for IsInfinity, removal of GetInputRate() and GetOutputRate()

architecture/api/DspFaust.cpp, architecture/faust/audio/oboe-dsp.h
As discussed in #691, when a disconnection event occurs processing in oboe stops. This PR attempts to re-init oboe again in that case. From testing on a couple of devices this seems to work as intended.
I've also added the `ANDROID_DRIVER` to the default constructor since that allows to init `DspFaust` without any sample rate and buffer size, both of which are not passed on to the oboe driver anyway currently. This saves some setup in the consuming Android app too.
=> Restart / reinit oboe when stream is disconnected

tools/faust2appls/faust2sc.py
fix: faust2sc.py: SuperNova plugins now compile with -DSUPERNOVA
=> fix: faust2sc.py: SuperNova plugins now compile with -DSUPERNOVA

compiler/generator/interpreter/fbc_llvm_compiler.hh, compiler/generator/llvm/clang_code_container.cpp, compiler/generator/llvm/llvm_code_container.cpp, compiler/generator/llvm/llvm_dsp_aux.cpp, compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp, compiler/generator/llvm/llvm_instructions.hh
Hi,
I tried building against LLVM 15 but it currently fails... 
I marked the places which changed and that I could not fix, pretty much only IRBuilder, but my LLVM-fu is not high enough to understand what a correct fix would be..
I also replaced the LLVM_XX macros by LLVM_VERSION_MAJOR checks (which have been there since llvm 3.1, from what I could see the earliest macros in the code refer to 3.4)
=> Initial work for LLVM 15, also refactor the LLVM version macros

build/Make.llvm.static
I noticed when updating Homebrew formula to 2.40.0 (https://github.com/Homebrew/homebrew-core/pull/98755) where parallel build is default behavior.
Repeated builds would produce different total size, e.g.
```
🍺  /usr/local/Cellar/faust/2.40.0: 1,469 files, 247.2MB, built in 2 minutes 49 seconds
```
```
🍺  /usr/local/Cellar/faust/2.40.0: 1,469 files, 250.6MB, built in 2 minutes 54 seconds
```
Running deparallelized showed 264.3MB:
```
🍺  /usr/local/Cellar/faust/2.40.0: 1,469 files, 264.3MB, built in 12 minutes 10 seconds
```
---
I believe the issue is that the `$(FOLDERS)` and  `$(OUTPUT)` are allowed to run in parallel, so the number of LLVM libraries extracted is non-deterministic by the time `libfaustwithllvm.a` is created.
To avoid this, the `$(OUTPUT)` should depend on `$(FOLDERS)`
=> fix parallel build of Make.llvm.static

architecture/lv2.cpp
This adds support of the following metadata to turtle mappings:
* [tooltip Example] => rdfs:comment "Example"
* [scale:log] => lv2:portProperty epp:logarithmic
* [lv2:enumeration] => lv2:portProperty lv2:enumeration
Closes #730.
=> lv2.cpp: support tooltip, scale and enumeration metadata

compiler/libcode.cpp
@sletz Wasn't able to build after updating to latest commit on `master-dev`. Looks like just a few missing spots from [recent refactoring](https://github.com/grame-cncm/faust/commit/37a8d272bb837266df718593facd9636e630b97a). First commit so please let me know if anything else is expected for PRs!
=> Add more `OCPP_BUILD` checks to fix undefined `old_comp` in `compiler/libcode.cpp`.

tools/faust2appls/faust2sc.py
The guessing mechanism was missing the "include" part of the headerpath guess which is the subfolder the folders it is looking for exists in in the supercollider repo
=> fix: faust2sc.py missing "include" part of header path in guess

tools/faust2appls/faust2bela
this is needed if the linker uses the static version of libHTTPDFaust , at which point it won't know about its dependency on libmicrohttpd. I checked the other faust2appls and they are all doing it correctly already, the issue was only with faust2bela.
=> Bela: add -lmicrohttpd alongside -lHTTPFaust.

architecture/ladspa.cpp
* Set LADSPA descriptor fields `Name`, `Maker`, `Copyright` from FAUST global metadata `name`, `author`, `copyright`/`license` fields, if present.
* Set `Maker` to empty string, not `"undefined"`, if not present.
Note: I'm no C/C++ expert, but I took care copy the descriptor info from the global FAUST metadata in a safe way. Please review the changes with this in mind.
=> fix: ladspa architecture file to set descriptor info from metadata

architecture/ladspa.cpp
I'm sorry, I messed up the changes in #807. They contain typos in the function names and improper types. I must have copy-and-pasted an outdated untested version of the file.
This PR fixes this.
Note to self: do not use the Github web editor again! ;-/
=> fix: mix-up of changes to ladspa.cpp in #807

architecture/faust/dsp/dsp.h, architecture/faust/dsp/libfaust-box.h, architecture/faust/dsp/libfaust-signal.h, architecture/faust/gui/UI.h
Fixing a few unused var warnings I get in these public-facing files.
=> Fix some unused var compiler warnings

compiler/generator/jax/jax_code_container.cpp, compiler/generator/jax/jax_code_container.hh, compiler/generator/jax/jax_instructions.hh
* Remove re-implementation of inlineSubcontainersFunCalls because I had only changed it due to an earlier bug which is now fixed.
* Remove the definition of \_\_call\_\_ from `jax_code_container.cpp` because it's in architecture files
I tested impulse-tests on macOS.
=> JAX backend patches 001

architecture/jax/minimal.py, compiler/generator/jax/jax_code_container.cpp, compiler/generator/jax/jax_instructions.hh, tests/impulse-tests/archs/impulsejax.py
There's a problem with the current code at this line:
https://github.com/grame-cncm/faust/blob/3af02793c9b6c2244f6e9d38082819b511936d80/architecture/jax/minimal.py#L111
The label isn't unique so multiple things try to write to the same intermediate variable. I'm talking about the intermediate variables `mod_vars` [here](https://github.com/grame-cncm/faust/blob/3af02793c9b6c2244f6e9d38082819b511936d80/architecture/jax/minimal.py#L157).
Consider this Faust code:
```faust
import("stdfaust.lib");
// Define the number of sections
N = 3;
// Define the parameters for each section.
gains = 0, 0, 0;
freqs = 500, 5000, 10000;
bandwidths = 100, 5000, 5000;
section(i) = hgroup("Section %i",
fi.peak_eq(
vslider("Gain", gains : ba.selector(i, N), -80., 12., .001),
vslider("Freq",  freqs : …
```
=> Fix accidental clashing intermediate JAX variables

architecture/jax/minimal.py, tests/impulse-tests/archs/impulsejax.py
`int(jnp.round(x))` is bad with jax's JIT, so I changed it to `int(round(x))`.
I also moved `add_button` before `add_nentry` and `add_slider` because the latter two have more in common.
=> Fix JAX JIT issue

architecture/cpal.rs, architecture/jack.rs, architecture/minimal.rs, architecture/portaudio.rs, compiler/generator/rust/rust_code_container.cpp, tools/faust2appls/faust2cpalrust, tools/faust2appls/faust2jackrust, tools/faust2appls/faust2portaudiorust
Add the ability to allocate directly on the heap with default-boxed.
Fixes #804
At the moment, there is no formal way to allocate an arbitrary struct on the heap in rust. The current approach taken by Faust is to allocate the dsp with `Box::new(Dsp::new())` which would be expected to first allocate on stack then move on heap, but this move is optimized away in release and it's allocated directly on the heap. However, when running in debug mode, the intermediary allocation is here making any echo or reverb very likely to stack overflow.
This PR adds a way to allocate the DSP on the heap with the help of the third-party crate [default-boxed](https://docs.rs/default-boxed/latest/default_boxed/).
The change in the generated code of Faust is very conservative: It's under conditional …
=> Rust: Allocate on the heap with default-boxed

compiler/libcode.cpp
I found this when using a static error message string across multiple calls to `DSPToBoxes`.
=> Clear error message after successful parse in `DSPToBoxes`, to allow for reuse of error string across multiple calls

architecture/faust/gui/JuceReader.h
The `juce::File` constructor expects an absolute path on Windows systems, but accepts relative paths on macOS / Linux.
Calls to the `juce::File` constructor have been replaced with `juce::File::getCurrentWorkingDirectory().getChildFile(path_name)`, which should get the CWD and open the filepath relative to it, or, in the case that `path_name` is an absolute path, will open that absolute path and return a `juce::File` object.
=> Fix JUCE file opening on Windows

architecture/api/DspFaust.cpp
When `JUCE_DRIVER` and `OSCCTRL` are both defined, the `OSCUI` class is not created, but it is referenced in the implementation of `osc_compute_callback`. This commit moves the implementation into the if block where `OSCUI.h` is included, as it is in other files in the Faust ecosystem.
=> Move osc_compute_callback to fix compilation with JUCE + OSC

tools/faust2appls/faust2sc.py
gcc searches for multiple positions of headers given a path 
this pr broadens the test for supercollider headers so that the script does not cause a false negative about not found supercollider headers
=> faust2sc broaden test for supercollider headers

compiler/generator/rust/rust_code_container.cpp
After https://github.com/rust-lang/rust/pull/102750 , Rust reorders
fields in repr(Rust) structures based on size/alignment. Applying such
reordering to the Dsp struct substantially hurts performance.
Set repr(C) on the Dsp struct to recover that performance.
See
https://internals.rust-lang.org/t/unexpected-3-x-performance-regression-starting-with-rust-version-1-67/18724
for the test case and investigations that led to this.
=> Set repr(C) on the Dsp struct to recover performance

architecture/daisy/ex_faust.cpp
When using the `-patch` and `-pod` arguments, the build will fail because the `Configure` method has been deprecated in the latest Daisy SDK.
Closes #868
=> Removes deprecated method that fails daisy build

.github/workflows/libfaust.yml
In this change we build ncurses 6.4 locally rather than `yum install -y ncurses-devel`. This helps downstream Linux applications work correctly.
=> Use ncurses 6.4 when building LLVM

tools/faust2appls/faust2cagtk, tools/faust2appls/faust2caqt, tools/faust2appls/faust2jack, tools/faust2appls/faust2jaqt
My [previous PR](https://github.com/grame-cncm/faust/pull/900) doesn't actually run.
```zsh
faust2jaqt  test.dsp && ./test
cat: test_tmp.cpp: No such file or directory
```
I missed this originally because I made a subtle mistake in my nixos-pkg.  Long story...
=> fix thread-safe preset management

architecture/faust/gui/MapUI.h
The `MapUI.h` architecture file has a few spots where it needs to get/set a parameter value from a `std::map<std::string, FAUSTFLOAT*>`. Previously this was being done with the pattern:
```cpp
if (fPathZoneMap.find(str) != fPathZoneMap.end()) {
return *fPathZoneMap[str];
}
```
With this approach, both `fPathZoneMap.find(str)` and `fPathZoneMap[str]` are re-doing the same work of finding the relevant entry in the map, which is a $\mathcal{O}(\text{log}(n))$ operation in the size of the map.
This PR re-writes that pattern as
```cpp
const auto fPathZoneMapIter = fPathZoneMap.find(str);
if (fPathZoneMapIter != fPathZoneMap.end()) {
return *fPathZoneMapIter->second;
}
```
So the work of finding the entry in the map only happens once.
=> MapUI: remove redundant map lookups

architecture/webaudio/webaudio-wasm-wrapper.js
This fixes an error while using pitchbend / pitchwheel in WASM MIDI polyvoice setup.
Previous pitchbend related changes in commit [4caac9a17681513e81b3691fac21c8dccf5e9e30](https://github.com/grame-cncm/faust/commit/4caac9a17681513e81b3691fac21c8dccf5e9e30). The previous commit changed `path` to `pw.path` in a few places but looks like one of the places wasn't updated, hence the bug.
=> WebAudio: Fix pitchbend bug in webaudio-wasm-wrapper.js

compiler/libcode.cpp
Dangling brace introduced in https://github.com/grame-cncm/faust/commit/f7b8c945ba25996a7fedda50456432700558a5e0
=> Add missing closing brace in preprocessor directive to fix `libcode.cpp`

architecture/faust/gui/JuceGUI.h
When trying a faust structure with tabs within tabs I hit an assert in juce_TabbedButtonBar.cpp in line 248. This is because the added tab didn't have a name since it was created with openTabBox which in contrast to openVerticalBox or openHorizontalBox doesn't have a label assigned to it.
Fixed this by adding setName to the constructor of uiTabBox but maybe there is a better way to do this since all the other constructors are empty and these type of things are done through member initializers.
Hope this helps.
JuanS
=> JuceAssertWhenUsingTabs

compiler/generator/rust/rust_code_container.cpp
In the generated code for the rust backend, the strings are currently stored as normal string. This leads some special strings, such as Windows file paths to potentially include encoding characters due to backslashes.
Storing them as [raw string literals](https://doc.rust-lang.org/rust-by-example/std/str.html#literals-and-escapes) is a safe way to ensure that the in-memory string is correctly translated in the rust compiler.
Before:
```rs
m.declare("compile_options", "-a C:\Users\Pierre\AppData\Local\Temp\.tmpq2mSuW -lang rust -ct 1 -es 1 -mcd 16 -single -ftz 0");
```
After:
```rs
m.declare("compile_options", r"-a C:\Users\Pierre\AppData\Local\Temp\.tmpq2mSuW -lang rust -ct 1 -es 1 -mcd 16 -single -ftz 0");
```
=> Rust backend: store metadata values as raw strings

tools/faust2appls/faust2jackconsole
The `faust2jackconsole` script didn't have an effects option. Fixing. Also, fixing compile error b/c `-ldl` was missing from the linker options.
=> Update faust2jackconsole to allow effects option

architecture/dplug.d
This fixes linking of parameters between Faust and Dplug and allows access to the faust dsp module from a sub-class of FaustClient.
=> small tweaks to dplug architecture file

documentation/misc/using-faust-with-ros-src/chapters/introduction.tex, documentation/misc/using-faust-with-ros-src/chapters/messages.tex
This pull request fixes typos in documentation folder. I kindly request repository maintainers to  review and merge it.
equipments -> equipment 
For more informations -> For more information 
chararacter -> character
=> fixed typos from documentation

architecture/comparator/README.md, architecture/comparator/compclass.cpp, architecture/comparator/minimal-fixed-point.cpp, architecture/comparator/minimal-floating-point.cpp, architecture/faust/dsp/fixed-point.h, build/CMakeLists.txt, compiler/generator/type_manager.hh, compiler/interval/intervalAdd.cpp, compiler/interval/intervalEq.cpp, compiler/interval/intervalGe.cpp, compiler/interval/intervalGt.cpp, compiler/interval/intervalMul.cpp, compiler/interval/intervalNe.cpp, compiler/interval/intervalPow.cpp, compiler/interval/interval_def.hh, compiler/interval/utils.hh, tools/README.md, tools/faust2appls/faust2comparator
Adds support for integer intervals on the interval library (with proper representation of wrapping behaviour).
Corrects (once again) definition of fixed-point types and MSB.
Adds a tool (faust2comparator) that allows to compare outputs of fixed-point and floating-point versions of programs, both sample-wise and on sound files.
=> Improvements on the interval library and comparison tool

architecture/jax/minimal.py, compiler/generator/jax/jax_code_container.cpp, tests/impulse-tests/Make.jax, tests/impulse-tests/archs/impulsejax.py
* fix bug in `jax_code_container.cpp` in which static sig tables got used before they were initialized
* turn off the JAX `bells.dsp` impulse-test due to inaudible precision issues
* refactor JAX architecture files for clarity
=> Update JAX backend and architecture

architecture/jax/minimal.py, compiler/generator/jax/jax_code_container.cpp, compiler/generator/jax/jax_code_container.hh, tests/impulse-tests/archs/impulsejax.py
Previously, when using soundfiles with JAX, the url file path needed to be either absolute or relative to the python file. Now it's possible to pass a list of directories in which to search for the files. I've tested the following usage in DawDreamer.
```python
module_name = "FaustModule"
with FaustContext():
jax_code = boxToSource(box, 'jax', module_name, ['-a', 'jax/minimal.py'])
custom_globals = {}
exec(jax_code, custom_globals)
Model = custom_globals[module_name]
soundfile_dirs = ["/Users/admin/assets", ["/Users/admin/more_assets"]
model = Model(44100, soundfile_dirs)
model = Model(sample_rate=44100, soundfile_dirs=soundfile_dirs)
model = Model(44100)
```
=> JAX: improve soundfile path searching

.github/workflows/libfaust.yml, .github/workflows/macos.yml, .github/workflows/ubuntu.yml, .github/workflows/windows.yml, build/misc/llvm.cmake, embedded/faustgen/CMakeLists.txt
It succeeded here: https://github.com/DBraun/faust/actions/runs/6844214830
* mpg123 is not installed anymore for macos arm64.
* QT5 is installed with a dedicated github action instead of brew. We can do this on the FaustLive repo too soon.
* LLVM caching was slightly cleaned up.
Earlier today I was also trying to get an ubuntu aarch64 libfaust working but ran into issues, so I'm just submitting this simpler PR.
=> Fix mpg123 issue on macos arm64 github action

tests/llvm-tests/Makefile
Based on findings by @jcelerier Thanks again!
Fixed in ossia/faust-tester: https://github.com/ossia/faust-tester/commit/c780137171e2bc098026cbbf19072c4888a6daa3
=> Fix segfault in llvm-tests on linux

architecture/faust/audio/rtaudio-dsp.h
From version 6.0.0 RtAudio stopped using exceptions, this PR provides support in the `rtaudio-dsp.h` driver for this new error handling/reporting system in a backwards compatible way.
Has been discussed in [issue-978](https://github.com/grame-cncm/faust/issues/978)
=> support rtaudio ver > 6.0 in rtaudio-dsp.h driver

compiler/normalize/simplify.cpp
These BinOp's can optimize out the isMinusOne/isZero operands, but since the xxxNeutral/Absorbing predicates take a single argument they can't check another operand and take isOne() into account, so this patch adds the brute force check into simplification.
Random example,
process = _ <: ==(1) | ==(2) <: &(1==1), |(2!=3);
compiles to
float fTemp0 = float(input0[i0]);
int iTemp1 = (fTemp0 == 1.0f) | (fTemp0 == 2.0f);
output0[i0] = FAUSTFLOAT(iTemp1 & 1);
output1[i0] = FAUSTFLOAT(iTemp1 | 1);
after this patch we have
float fTemp0 = float(input0[i0]);
output0[i0] = FAUSTFLOAT((fTemp0 == 1.0f) | (fTemp0 == 2.0f));
output1[i0] = FAUSTFLOAT(1);
Should the new isSigBool() function have the "int max_recursion" argument?
=> teach kAND/kOR to optimize &(1) and |(1)

tools/physicalModeling/mesh2faust/CMakeLists.txt, tools/physicalModeling/mesh2faust/README.md, tools/physicalModeling/mesh2faust/src/main.cpp
Also fixes Eigen dirs not being included in executable target. (It was only included with library).
Fixes https://github.com/grame-cncm/faust/issues/986
=> mesh2faust: Fix out-of-order arg in main.

architecture/faust/dsp/libfaust-signal-c.h
Fixes "unknown type name 'SType'" make errors for projects that include `faust/dsp/llvm-dsp-c.h`.
=> Fix CsigFFun API declaration

.github/workflows/libfaust.yml, Dockerfile-aarch64, build/Make.llvm.static
Most recent GitHub action run: https://github.com/DBraun/faust/actions/runs/8501382693
This adds a GitHub action job for ubuntu aarch64.
The ubuntu x86 job now uses LLVM 15 from apt-get.
For GitHub actions, it also raises the macOS version to 12 (Monterey) since macOS 11 has been deprecated on GitHub actions. @sletz showed me an earlier failed run due to this issue.
The Windows job now uses LLVM 17.0.6
Do not merge until I or someone confirms that the new builds are built entirely statically.
=> Add GitHub action for Ubuntu aarch64

architecture/rust/README.md
The allocation issue explanation was focused on the change from before the introduction of default-boxed, this PR rewrites it from the perspective of how it is now, and adds explanation on how to opt out of the feature
=> Faust: Update the memory allocation issue doc

architecture/ca-console.cpp, tools/faust2appls/faust2caconsole
Added coreaudio / console support, derived from Core Audio / GTK, with the GTK part replaced by Console.
This allows local development on Mac OS without dependencies on GTK or QT.  To access a graphical UI, enable Httpd.
Tested to work on Intel/Catalina (2012 MBP) with midi, httpd.  The Core Audio part from Core Audio + GTK is untouched, so it should work with newer Mac computers and OS.
3 lines commented out for Fix Point support, as I'm unsure how this can be tested.  In theory uncommenting them will work.
=> Added Core Audio + Console architecture

architecture/stratus.cpp, tools/faust2appls/README.md, tools/faust2appls/faust2stratus
Hi
I would like to contribute an Architecture file and a faust2xxx script targeting the [Chaos Audio Stratus Effects] pedal(https://chaosaudio.com/products/stratus). 
Chaos Audio has recently opened up a [developers portal](https://github.com/chaosaudio/Dev-Portal) that encourages people to build their own effects. They strongly recommend Faust as the medium for doing this. I myself have built an ["SDK" for effects development](https://github.com/bassmanitram/faust-stratus) that includes (variations on) the two files that I am contributing here. That SDK vastly simplifies the effects creation workflow, while I am also writing a WiKi on that same repo instructing developers on the usage of Faust and the SDK for quickly getting their effects compiled and installed on the pedal.
Having the …
=> Create arch file and faust2xxx script for Chaos Audio Stratus Pedal

architecture/chaos-stratus/_pedal-tools.sh, architecture/chaos-stratus/build-effect.sh, architecture/chaos-stratus/build-install-effect.sh, architecture/chaos-stratus/install-effect.sh, architecture/chaos-stratus/stratus.cpp, tools/faust2appls/faust2stratus
* Move the architecture stuff to folder 'chaos-stratus'
* Implement a set of tools for connecting to and executing commands on the pedal
* Adapt faust2stratus to use those tools
Eventually the faustservice Makefiles for the Stratus will also use those tools
=> Large refactor to allow for "helper" scripting

architecture/chaos-stratus/build-effect.sh, architecture/chaos-stratus/build-install-effect.sh, architecture/chaos-stratus/install-effect.sh
realpath is cool, but it hasn't become ubiquitous yet, so I replace it with a more widely compatible technique to get a scripts home location.
=> Remove use of realpath

architecture/puredata.cpp
Continuation of https://github.com/grame-cncm/faust/pull/1034.
Tries to address the issues raised in https://github.com/grame-cncm/faust/pull/1034#issuecomment-2225892623.
First, make the first inlet a pure message inlet, so users can not accidentally connect it to a signal.
As a second step, add the `MESSAGE_INLET` macro to control the behavior of the first inlet at compile time.
If 0, the first inlet is a signal inlet and also takes messages, which is more idiomatic, but not backwards compatible.
If 1, keep the old behavior (= default).
=> Pd multichannel improvements

architecture/puredata.cpp, tools/faust2appls/faust2puredata
See https://github.com/grame-cncm/faust/pull/1037#issuecomment-2228487205
I've renamed `MESSAGE_INLET` to `NEWIO` because the new behavior changes both the inlet and outlet structure. (The old behavior is still the default due to backwards compatibility.)
I've also renamed '-msi'  to '-newio' in 'faust2puredata' script. If you find a better name, feel free to edit :)
@alainbonardi I'm pretty optimistic that I didn't break anything, but to be 100% sure, please test again with the four combinations.
=> pd: fix outlet order regression

compiler/generator/code_container.cpp
currently printMacros declares in rust constants that have the type i32 but those variables represent vector/array length as such their usage is usually at places where usize is expected. additionally they cannot be negative.
=> rust const definitions should use usize

compiler/generator/rust/rust_code_container.cpp, compiler/generator/rust/rust_code_container.hh, compiler/generator/rust/rust_instructions.hh
The benefit of using arrays as function arguments is that they fail compilation if a wrong length array is provided.
When the compute_arrays function is used then we have one less possible panic.
=> rust: provide a compute_arrays function

architecture/unity/FaustPolyUtilities_template.cs, architecture/unity/FaustUtilities_template.cs
The utility code generated by faust2unity fails to parse the most recent changes to embedded JSON metadata, particularly the "size" key, which should be ignored.   This patch skips unknown JSON metadata keys as long as they are double-quoted string values or numbers.
In addition, I've added basic compatibility for VisionOS (ie, macro checks now allow for UNITY_VISIONOS) which result in VisionOS projects using ios libs.
=> add unity visionOS compatibility and fix unity utilities JSON parser to handle unexpected values

compiler/generator/code_container.cpp, compiler/generator/rust/rust_code_container.cpp
This commit removes the -uim flag for rust
and provides the const values by default
and makes use of these const values
in get_num_inputs and get_num_outputs
it also simplifies how this functions are generated they are now just a string
To create arrays for compute_arrays() one needs to know the array sizes at compile time. The const definitions provide these.
=> Always provide const values for rust

compiler/generator/rust/rust_code_container.cpp, compiler/generator/rust/rust_code_container.hh, compiler/generator/rust/rust_instructions.hh
faust code generation should not specify traits.
this pr introduces this change.
It is tested against the impulse-tests using the architecture file in its subfolder.
How much architecture files need to change depends on how traits are used.
The jack cpal and minimal architecture files could be compiled after minimal changes, 
but need more cleanup work.
=> Rust code generation independent of FaustDsp trait

compiler/generator/rust/rust_code_container.cpp, compiler/generator/rust/rust_instructions.hh, tests/impulse-tests/Make.rust
solve unimportant warning 
and 
and solve regression because of fix for #1060.
adding osc_enable.ir to rust impulse tests revealed a mistake in the fix for #1060
This PR removes brackets around if when it is not from a select2 instruction.
=> Fix regression because of  #1061

architecture/daisy/Makefile, architecture/daisy/README.md, architecture/faust/midi/daisy-midi.h
This PR suggest a fix for issue #1084 
> daisy_midi class of daisy architecture is outdated
=> Updated class daisy_midi to be compatible with libDaisy v7.1.0

.github/workflows/ubuntu.yml, tests/impulse-tests/Make.gcc, tests/impulse-tests/Make.interp, tests/impulse-tests/Makefile
based on #1068 
a lot of work was caused by #1075
=> 2b) add cpp and rust tests on ci 

.github/workflows/ubuntu.yml, compiler/generator/rust/rust_code_container.cpp, compiler/global.cpp, compiler/global.hh, tests/impulse-tests/Make.gcc, tests/impulse-tests/Make.interp, tests/impulse-tests/Makefile, tests/impulse-tests/archs/rust/architecture_normal.rs
This PR introduces the new compile flag `-rnt`  `--rust-no-faustdsp-trait` to faust, to not generate the FaustDsp interface.
The aim is to be able to make use of flags like `-ec` or `-os` that change the generated code so that it is not compatible with the FaustDsp trait. 
@bluenote10 
@obsoleszenz
=> 2) Make Rust FaustDsp Trait Optional

compiler/generator/instructions_compiler.cpp, compiler/generator/rust/rust_code_container.cpp, compiler/generator/rust/rust_code_container.hh, compiler/generator/rust/rust_instructions.hh, compiler/global.cpp, tests/impulse-tests/Makefile, tests/impulse-tests/archs/rust/architecture_cm.rs, tests/impulse-tests/archs/rust/architecture_ecrnt.rs, tests/impulse-tests/archs/rust/architecture_inpl.rs, tests/impulse-tests/archs/rust/architecture_osecrnt.rs, tests/impulse-tests/archs/rust/architecture_trait.rs
In rust it is not possible to have two references to the same buffer if one is mutable. 
This makes it impossible to write to the same place from which one reads, if one wants to have different variables holding references to do so.  This is the case for our input and output buffer references in the compute function.
To circumvent this limitation of rust I propose to introduce a different compute interface if the `-inpl` flag is used.
I propose to have a single variable for input and output.
Instead of `pub fn compute(&mut self, count: usize, inputs: &[&[FaustFloat]], outputs: &mut [&mut [FaustFloat]])`, I propose: `pub fn compute(&mut self, count: usize, outputs: &mut [&mut [FaustFloat]])` 
Or to be more precise for the case PR #1087 is accepted:
```
pub fn compute<IOType>(
&mut self, …
```
=> 6) Rust: make `-inpl` possible

.gitmodules, Makefile, build/CMakeLists.txt, build/Makefile, build/lint.query
@sletz I figured out a CMake integration for the pointer nondeterminism lint I mentioned to you. I did it by wrapping clang-query into a clang plugin, so that a query can be automatically converted into a compiler warning. The plugin is at https://github.com/nuchi/node-matcher-plugin
(Context for others: code generation is nondeterministic because sometimes the compiler will compare pointers in situations where it needs to arbitrarily choose one. But pointers are generated by malloc/new and therefore change from run to run. One way to eliminate this non-determinism is to not compare pointers. But that can be hard to detect. Hence this new lint step.)
Adds a compiler warning for doing a pointer comparison between `CTreeBase*` or `Symbol*`, in order to better find where nondeterminism is …
=> Add lint for nondeterministic pointer comparison

architecture/faust/dsp/poly-dsp.h, architecture/faust/gui/DecoratorUI.h, architecture/faust/gui/MidiUI.h, architecture/faust/gui/UI.h, tools/faust2appls/faust2daisy
Adressing Issue #1090 
When testing the PR #1105 my libDaisy repo was not up to date. 
I updated to commit bd13385 and found out that the newly introduced compiler flag "DAISY" creates a naming conflict, since "DAISY" is used in an enum of libDaisy 
` /libDaisy/src/sys/system.h:161:14: error: expected identifier before ',' token
161 |         DAISY,`
renamed the preprocessor FLAG to DAISY_NO_RTTI for a  more unique name.
=> Fixing naming conflict of DAISY preprocessor flag of the newer libDaisy master branch

compiler/errors/errormsg.cpp, compiler/parser/faustparser.cpp, compiler/parser/faustparser.y
This allows "jump to error" functionality in many IDEs / editors.
=> Change error message format to $file:$line

compiler/errors/exception.hh
This simplifies the #if check in `exception.hh` so that it will not need to be modified for other platforms which don't use glibc.
=> Change execinfo.h check to depend on __GLIBC__ being defined

tools/physicalModeling/mesh2faust/src/mesh2faust.cpp, tools/physicalModeling/mesh2faust/src/mesh2faust.h
This allows users to compute the modal model separately from the DSP code. It is technically API-breaking since the existing `modal2faust` response changes from a `Response` type to a `std::string`, but I doubt anyone else is using these extra methods. The main intended API is the `mesh2faust` methods, which haven't changed. The only thing missing from the `Response`-typed response is the `ModalModel` they passed into the method anyway.
=> Add new `mesh2faust` API method to generate modal model and Faust DSP code independently

tools/physicalModeling/mesh2faust/src/mesh2faust.cpp
Simplify code generation to share an unscaled mode frequency table regardless of frequency control. Adds a divide per frequency calculation at runtime in exchange for clarity/simplicity.
=> [mesh2faust] Simplify mode frequency scaling

README.md
Location of `library.pdf` under ## Documentation and Resources was incorrect or out of date.
=> Corrected documentation information

architecture/chaos-stratus/_pedal-tools.sh, architecture/chaos-stratus/build-install-effect.sh
The installer scripts inadvertently used some bash extensions to posix shells. This made the scripts invalid when running with posix shells that are not bash. Unfortunately Ubuntu has, for some weird reason, decided that the default shell - /bin/sh - shall be dash not bash. And WSL is essentially Ubuntu! Which means the scripts don't work on Windows.
This PR replaces Bash specifics with their Posix (and Dash-compatible) alternatives.
It is fairly urgent to get this out to the Faust IDE because the main use case of this is building an installer from the IDE.
=> Make more posix complaint

compiler/generator/rust/rust_code_container.cpp
move dsp struct to the beginning of the exported code so that the use can use the architecture file to pass derive macros
=> rust: move dsp struct

compiler/DirectedGraph/DirectedGraph.hh
Fixes https://github.com/grame-cncm/faust/issues/1144.
=> Add missing cstdint include required by gcc 15

compiler/generator/rust/rust_instructions.hh
in rust: currently waveforms are stored in a mutable static variable that doesn't need to be mutable. this pr fixes this.
=> rust: fix unecessary mutablity for waveforms

compiler/generator/interpreter/fbc_compiler.hh
```
faust/compiler/generator/interpreter/fbc_compiler.hh:81:49: error: pragma message requires parenthesized string
81 | #pragma message("warning pure Interpreter mode");
|                                                 ^
```
=> fbc: fix build error with clang 20 on windows
